### ISSUE TITLE
Error running read-decrypted-sfz.py

### ISSUE THREAD

**Issue by eakwarren** [CarlGao4/Muse-Sounds#2]
### System info:
Win 11 Pro 23H2 OS Build 22631.2861
MuseScore Studio version (64-bit): 4.3.2-241630831
MuseSamplerCoreLib.dll v0.6.3
Python 3.12.4
Frida 16.3.3

### Steps to reproduce:
Open MuseScore Studio and load orchestral template with Muse Sounds
Open PowerShell as administrator
Run python read-decrypted-sfz.py
Powershell outputs the following
MuseScore Studio quits

### PowerShell output:
```
PS C:\Users\eric\Downloads> python .\read-decrypted-sfz.py
Traceback (most recent call last):
  File "C:\Users\eric\Downloads\read-decrypted-sfz.py", line 34, in <module>
    session = frida.attach("MuseScore4.exe")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eric\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\__init__.py", line 95, in attach
    return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eric\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\eric\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\core.py", line 1071, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.ProcessNotRespondingError: process with pid 10612 either refused to load frida-agent, or terminated during injection
PS C:\Users\eric\Downloads>
```

**Comment by CarlGao4** [comment]
This error may have various causes and I can do nothing to help currently. Maybe you should try to google and find out what happened by yourself.

**Comment by eakwarren** [comment]
I have been. Thanks anyway.
